name: Windows Build and Release

on:
  push:
    tags:
      - 'v*'    # 当推送类似 v1.0.0 的标签时自动触发
  workflow_dispatch:    # 允许手动触发

permissions:
  contents: write   # 授予内容的写权限，必要的，用于创建发布

jobs:
  build-and-release:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --distpath dist/ main.py

    - name: Package files into ZIP
      shell: powershell
      run: |
        $zipPath = "dist\Cloudflare2HuaweiDNS.zip"
        $filesToZip = @("dist\main.exe", "config.yaml")
        Compress-Archive -Path $filesToZip -DestinationPath $zipPath

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cloudflare2HuaweiDNS
        path: dist/Cloudflare2HuaweiDNS.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name || 'manual-trigger' }}
        release_name: Release ${{ github.ref_name || 'Manual Trigger' }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Cloudflare2HuaweiDNS.zip
        asset_name: Cloudflare2HuaweiDNS.zip
        asset_content_type: application/zip
